.TH macfand 1 "June 25, 2022" "Version 1.0.0" "USER COMMANDS"
.SH NAME
macfand \- Fan control for Apple computers running Linux.
.SH SYNOPSIS
.B macfand
[\-nfd]
.SH DESCRIPTION
macfand is a daemon that reads temperature sensors and adjust the fan(s) speed on Apple computers. macfand is configurable and logs temp and fan data to a file. macfand has 2 modes of operation for controlling a fan:


.RS
.TP
\- Set speed based on temp average from all available sensors

.TP
\- Set speed based on temp average from a configured group of sensors
.RE

These modes can be configured per fan, using the latter listed method is perfered for desktop machines with more than 2 fans as it allows more fine tuning for quietness or cooling performance.  macfand uses profiles to
provide a known working/tuned out of box experience, but allows for their presets to be overridden in the configuration file.


Important: macfand depends on the applesmc kernel module.

.SH OPTIONS
.TP
.B \-n 
runs macfand the in foreground, logging to stdout.
.TP
.B \-f
enables logging in farenhiet.
.TP
.B \-d
disables output colors (enabled by default in daemon mode)


.SH EXIT STATUS
macfand returns non-zero exist status in case of failure to start.
.SH FILES
.I /etc/init.d/macfand
.RS
.P
Daemon init script.
.RE
.I /usr/lib/systemd/system/macfand.service
.RS
.P
Systemd service

.RE
.I /etc/macfand.conf
.RS
.P
Configuration file that can be tuned to get desired working temperature. The format must be
.RE
.I /var/log/macfand.log
.RS
.P
Log file. When log_level is 1, the following ouput is generated:
.RE
.RE
.I /usr/local/macfand/machines
.RS
.P
Directory of profiles

.SH NOTES
To follow the log as it's written do

$ tail -F /var/log/macfand.log
.SH BUGS 

Please submit bug reports, comments and suggestions to:
https://github.com/ablakely/macfand/issues

.SH AUTHOR
Aaron Blakely (aaron@ephasic.org),
Ephasic Software (https://ephasic.org)
.SH "SEE ALSO"
tail (1) 

https://github.com/ablakely/macfand/wiki


