.TH macfand 1 "June 25, 2022" "Version 0.5" "USER COMMANDS"
.SH NAME
macfand \- Fan control for Mac Computers
.SH SYNOPSIS
.B macfand
.SH VERSION
MFDVERSION
[\-f]
.SH DESCRIPTION
macfand is a daemon that reads temperature sensors and adjust the fan(s) speed on Mac Pros. macfand is configurable and logs temp and fan data to a file. macfand uses three sources to determine the fan speeed: 1) average temperature from all sensors, 2) sensor TC0P [CPU 0 Proximity Temp and 3] and sensor TM0P [Memory Proximity Temp]. Each source's impact on fan speed can be individually adjusted to fine tune working temperature on different Mac Pros.

Important: macfand depends on applesmc-dkms.
macfand is a fork of macfanctld which is no longer mainted, macfand is geared towards Mac Pro systems but support for others is planned.
.SH OPTIONS
.TP
.B \-f
runs macfand the in foreground, logging to stdout.
.SH EXIT STATUS
macfand returns non-zero exist status in case of failure to start.
.SH FILES
.I /etc/init.d/macfand
.RS
.P
Daemon init script.
.RE

.I /usr/lib/systemd/system
.RS
.P
Systemd service

.RE
.I /etc/macfand.conf
.RS
.P
Configuration file that can be tuned to get desired working temperature. The format must be
.I <key>:<number>.

.I cpumem_min:
Minimum fan speed for the CPUMEM fan (fan1). Typically, this is set to 1500 (Apples default). Maximum speed is 2900.

.I expansion_min:
Minimum fan speed for the EXPANSION fan (fan2). Typically, this is set to 1900 (Apples default). Maximum speed is 2900.

.I exhaust_min:
Minimum fan speed for the EXHASUT fan (fan3). Typically, this is set to 1200 (Apples default). Maximum speed is 2900.

.I ps_min:
Minimum fan speed for the POWER_SUPPLY fan (fan4). Typically, this is set to 1200 (Apples default). Maximum speed is 2800.


.I temp_avg_floor:
Average temperature in Celsius at which the fan speed will be set to fan_min. Valid values are 0 to 90, and must be less than temp_avg_ceiling.

.I temp_avg_ceiling: 
Average temperature in Celsius at which the fan speed will be set to max (6200). Valid values are 0 to 90, and must be larger than temp_avg_floor.

.I temp_TC0P_floor:
Temperature in Celsius at TC0P, at which the fan speed will be set to fan_min. Valid values are 0 to 90, and must be less than temp_TC0P_ceiling.

.I temp_TC0P_ceiling:
Temperature in Celsius at TC0P, at which the fan speed will be set to max (6200). Valid values are 0 to 90, and must be larger than temp_TC0P_floor.

.I temp_TG0P_floor
:
Temperature in Celsius at TG0P, at which the fan speed will be set to fan_min. Valid values are 0 to 90, and must be less than temp_TG0P_ceiling.

.I temp_TG0P_ceiling:
Temperature in Celsius at TG0P, at which the fan speed will be set to max (6200). Valid values are 0 to 90, and must be larger than temp_TG0P_floor.

.I exclude: 
A list of natural numbers defining sensors that should be excluded from reading. Example:

exclude: 1 7

will disable reading of sensors temp1_input and temp7_input.

This feature was added as a workaround for issues in applesmc-dkms that disables reading of some sensors, or in some cases, incorrectly defines sensors that don't exists.

.I log_level values:
Set the log level. Valid values are:
 0 - Startup / Exit logging only
 1 - Basic temp / fan logging
 2 - Log all sensors
.RE

.I /var/log/macfanctl.log
.RS
.P
Log file. When log_level is 1, the following ouput is generated:

  Speed: [CPUMEM 1500] [EXPANSION 1900] [EXHAUST 1250] [POWER_SUPPLY 950],  AVG: 52.5C, *TC0P: 62.0C,  TG0P: 62.0C
  Speed: [CPUMEM 1500] [EXPANSION 1900] [EXHAUST 1250] [POWER_SUPPLY 950],  AVG: 52.4C, *TC0P: 62.0C,  TG0P: 61.8C
  Speed: [CPUMEM 1500] [EXPANSION 1900] [EXHAUST 1250] [POWER_SUPPLY 950],  AVG: 52.4C,  TC0P: 61.8C, *TG0P: 62.0C
  Speed: [CPUMEM 2810] [EXPANSION 2800] [EXHAUST 2750] [POWER_SUPPLY 2750],  AVG: 52.3C,  TC0P: 61.8C, *TG0P: 61.8C

Speed is the current fan speed. 

AVG, TC0P and TG0P shows the temperature in Celsius at the source. 

The '*' indicate which source that is currently driving the fan. 
.RE

.SH NOTES
Hopefully the provided configuration file will be suitable on most Mac Pros. However, there has been very little testing at this point. Therefore, enable logging and keep an eye on the temperatures in the log.

To follow the log as it's written do

$ tail -F /var/log/macfanctl.log
.SH BUGS 

Please submit bug reports, comments and suggestions to aaron@ephasic.org.

.SH AUTHOR
Aaron Blakely (aaron@ephasic.org)
.SH "SEE ALSO"
tail (1) 



